# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\OrSave\Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 504)
        MainWindow.setMinimumSize(QtCore.QSize(760, 430))
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border-radius: 5px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"    border-radius: 5px;\n"
"    color:rgb(185, 185, 185);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgba(209, 209, 209, 185);\n"
"    border-radius: 5px;\n"
"    color:rgb(185, 185, 185);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    outline:none;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,         stop:0 rgba(0, 121, 202, 255), stop:1 rgba(0, 205, 175, 255));\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(187, 16777215))
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"    border-radius:10px;\n"
"    background-color: rgba(253, 253, 253, 10);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(2, 2, -1, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(13, 14))
        self.pushButton.setMaximumSize(QtCore.QSize(13, 14))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255, 0, 0);\n"
"    border:1px solid rgba(113,17,15,50);\n"
"    border-radius:6px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(171, 0, 0);\n"
"    border-image: url(:/icon/close.svg);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(135, 0, 0);\n"
"}\n"
"\n"
"QPushButton:focus {outline: none;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(13, 14))
        self.pushButton_2.setMaximumSize(QtCore.QSize(13, 14))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(251, 255, 35);\n"
"    border:1px solid rgba(113,17,15,50);\n"
"    border-radius:6px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(189, 189, 0);\n"
"    \n"
"    border-image: url(:/icon/minus.svg);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(131, 131, 0)\n"
"}\n"
"QPushButton:focus {outline: none;}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(13, 14))
        self.pushButton_3.setMaximumSize(QtCore.QSize(13, 14))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 255, 127);\n"
"    border:1px solid rgba(113,17,15,50);\n"
"    border-radius:6px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 179, 0);\n"
"    \n"
"    border-image: url(:/icon/fullscreen.svg);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 116, 0)\n"
"}\n"
"\n"
"QPushButton:focus {outline: none;}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("font: 15pt \"阿里巴巴普惠体 3.0 55 Regular\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setStyleSheet("QListWidget{\n"
"    background-color: transparent;\n"
"    border:none;\n"
"    font: 11pt \"Alibaba PuHuiTi 3.0\";\n"
"}\n"
"\n"
"QListWidget::Item{\n"
"    color: rgb(255, 255, 255);\n"
"    height:40px;\n"
"    padding-left:4px;\n"
"}\n"
"\n"
"QListWidget::Item:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.068, y2:0, stop:0 rgba(0, 123, 201, 255), stop:0.495 rgba(0, 123, 201, 255), stop:0.505 rgba(0, 153, 192, 255), stop:1 rgba(0, 149, 193, 255))\n"
"}\n"
"\n"
"QListWidget::Item:selected{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.068, y2:0, stop:0 rgba(0, 123, 201, 255), stop:0.495 rgba(0, 123, 201, 255), stop:0.505 rgba(0, 153, 192, 255), stop:1 rgba(0, 149, 193, 255));\n"
"    \n"
"    color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QListWidget:focus{\n"
"    outline:none;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/file-copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/setting.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/info-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setStyleSheet("font: 9pt \"Alibaba PuHuiTi 3.0\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setStyleSheet("font: 7pt \"Alibaba PuHuiTi 3.0\";\n"
"color: rgb(230, 230, 230);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 10);\n"
"    border-radius:10px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setStyleSheet("font: 9pt \"Alibaba PuHuiTi 3.0\";\n"
"color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("font: 32pt \"Alibaba PuHuiTi 3.0\";")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget#page_2{\n"
"    background-color: transparent;\n"
"}")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setStyleSheet("font: 12pt \"Alibaba PuHuiTi 3.0\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"    border-radius:10px;\n"
"    background-color: rgba(255, 255, 255, 10);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton.setText("")
        self.radioButton.setAutoExclusive(True)
        self.radioButton.setProperty("saveName", "")
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_2.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_2.setText("")
        self.radioButton_2.setAutoExclusive(True)
        self.radioButton_2.setProperty("saveName", "")
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_3.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_3.setText("")
        self.radioButton_3.setAutoExclusive(True)
        self.radioButton_3.setProperty("saveName", "")
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_4.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_4.setText("")
        self.radioButton_4.setAutoExclusive(True)
        self.radioButton_4.setProperty("saveName", "")
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.horizontalLayout_3.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_5.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_5.setText("")
        self.radioButton_5.setAutoExclusive(True)
        self.radioButton_5.setProperty("saveName", "")
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_6.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_6.setText("")
        self.radioButton_6.setAutoExclusive(True)
        self.radioButton_6.setProperty("saveName", "")
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_7.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_7.setText("")
        self.radioButton_7.setAutoExclusive(True)
        self.radioButton_7.setProperty("saveName", "")
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_8.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_8.setText("")
        self.radioButton_8.setAutoExclusive(True)
        self.radioButton_8.setProperty("saveName", "")
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup.addButton(self.radioButton_8)
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_9.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_9.setText("")
        self.radioButton_9.setAutoExclusive(True)
        self.radioButton_9.setProperty("saveName", "")
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup.addButton(self.radioButton_9)
        self.horizontalLayout_3.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_10.setStyleSheet("\n"
"QRadioButton::indicator { \n"
"    width: 50px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    border-image: url(:/Placeholding/Placeholding/10972.png);\n"
"    border-radius:25px;\n"
"    background-color: rgb(83, 141, 217)\n"
"}\n"
"\n"
"")
        self.radioButton_10.setText("")
        self.radioButton_10.setAutoExclusive(True)
        self.radioButton_10.setProperty("saveName", "")
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup.addButton(self.radioButton_10)
        self.horizontalLayout_3.addWidget(self.radioButton_10)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.verticalLayout_12.addWidget(self.frame_5)
        self.frame_11 = QtWidgets.QFrame(self.page_2)
        self.frame_11.setStyleSheet("QFrame#frame_11{\n"
"    border-radius:10px;\n"
"    background-color: rgba(255, 255, 255, 10);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.listWidget1 = QtWidgets.QListWidget(self.frame_11)
        self.listWidget1.setStyleSheet("QListWidget{\n"
"    background-color: transparent;\n"
"    border:none;\n"
"    font: 11pt \"Alibaba PuHuiTi 3.0\";\n"
"}\n"
"\n"
"QListWidget::Item{\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left:4px;\n"
"}\n"
"\n"
"QListWidget::Item:hover{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.068, y2:0, stop:0 rgba(0, 123, 201, 255), stop:0.495 rgba(0, 123, 201, 255), stop:0.505 rgba(0, 153, 192, 255), stop:1 rgba(0, 149, 193, 255))\n"
"}\n"
"\n"
"QListWidget::Item:selected{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.068, y2:0, stop:0 rgba(0, 123, 201, 255), stop:0.495 rgba(0, 123, 201, 255), stop:0.505 rgba(0, 153, 192, 255), stop:1 rgba(0, 149, 193, 255));\n"
"    \n"
"    color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QListWidget:focus{\n"
"    outline:none;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"          border-width: 0px;\n"
"          border: none;\n"
"          background:rgba(64, 65, 79, 0);\n"
"          width:12px;\n"
"          margin: 0px 0px 0px 0px;\n"
"      }\n"
"      QScrollBar::handle:vertical {\n"
"          background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(20, 154, 198, 255), stop:1 rgba(0, 0, 0,0));\n"
"          min-height: 20px;\n"
"          max-height: 20px;\n"
"          margin: 0 0px 0 0px;\n"
"          border-radius: 6px;\n"
"      }\n"
"      QScrollBar::add-line:vertical {\n"
"          background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"          stop: 0 rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));\n"
"          height: 0px;\n"
"          border: none;\n"
"          subcontrol-position: bottom;\n"
"          subcontrol-origin: margin;\n"
"      }\n"
"      QScrollBar::sub-line:vertical {\n"
"          background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"          stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));\n"
"          height: 0 px;\n"
"          border: none;\n"
"          subcontrol-position: top;\n"
"          subcontrol-origin: margin;\n"
"      }\n"
"      QScrollBar::sub-page:vertical {\n"
"      background: rgba(64, 65, 79, 0);\n"
"      }\n"
"\n"
"      QScrollBar::add-page:vertical {\n"
"      background: rgba(64, 65, 79, 0);\n"
"      }\n"
"")
        self.listWidget1.setObjectName("listWidget1")
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Placeholding/Placeholding/10972.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.listWidget1.addItem(item)
        self.verticalLayout_10.addWidget(self.listWidget1)
        self.verticalLayout_12.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.page_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame1 = QtWidgets.QFrame(self.frame_12)
        self.frame1.setStyleSheet("QFrame#frame{\n"
"    background-color: rgba(255, 255, 255, 10);\n"
"    border-radius:10px;\n"
"}")
        self.frame1.setObjectName("frame1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.frame1)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.frame_10 = QtWidgets.QFrame(self.frame1)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.frame_10)
        self.widget_2.setMinimumSize(QtCore.QSize(71, 71))
        self.widget_2.setMaximumSize(QtCore.QSize(71, 71))
        self.widget_2.setStyleSheet("border-image: url(:/Placeholding/Placeholding/10972.png);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6.addWidget(self.widget_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addWidget(self.frame_10)
        self.verticalLayout_9.setStretch(1, 1)
        self.horizontalLayout_7.addWidget(self.frame1)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setStyleSheet("QFrame#frame_13{\n"
"    background-color: rgba(255, 255, 255, 10);\n"
"    border-radius:10px;\n"
"}")
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.frame_13)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_11.addWidget(self.label_21)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_7.setMinimumSize(QtCore.QSize(91, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_5.setMinimumSize(QtCore.QSize(91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_4.setMinimumSize(QtCore.QSize(91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_6.setMinimumSize(QtCore.QSize(91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_11.addWidget(self.pushButton_8)
        self.verticalLayout_11.setStretch(1, 1)
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.verticalLayout_12.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.page_3.setObjectName("page_3")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 80, 22))
        self.label_7.setStyleSheet("font: 12pt \"Alibaba PuHuiTi 3.0\";")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QWidget#page_4{\n"
"    background-color: transparent;\n"
"}")
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setStyleSheet("font: 12pt \"Alibaba PuHuiTi 3.0\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.frame_6 = QtWidgets.QFrame(self.page_4)
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 10);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setStyleSheet("font: 10pt \"Alibaba PuHuiTi 3.0\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_21.setMinimumSize(QtCore.QSize(100, 24))
        self.pushButton_21.setMaximumSize(QtCore.QSize(100, 24))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_4.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_22.setMinimumSize(QtCore.QSize(104, 24))
        self.pushButton_22.setMaximumSize(QtCore.QSize(104, 24))
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_4.addWidget(self.pushButton_22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.page_4)
        self.frame_7.setStyleSheet("QFrame#frame_7{\n"
"border-radius: 10px;\n"
"background-color: rgba(255, 255, 255, 10);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setStyleSheet("font: 10pt \"Alibaba PuHuiTi 3.0\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_23.setMinimumSize(QtCore.QSize(100, 24))
        self.pushButton_23.setMaximumSize(QtCore.QSize(100, 24))
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_5.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_24.setMinimumSize(QtCore.QSize(104, 24))
        self.pushButton_24.setMaximumSize(QtCore.QSize(104, 24))
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_5.addWidget(self.pushButton_24)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.frame_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setStyleSheet("font: 12pt \"Alibaba PuHuiTi 3.0\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.frame_8 = QtWidgets.QFrame(self.page_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setStyleSheet("font: 14pt \"Alibaba PuHuiTi 3.0\";")
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.verticalLayout_7.setStretch(1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMaximized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>关闭</p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>最小化</p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>全屏</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Ori 外置游戏存档"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "存档管理"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "存档备份"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "设置"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "关于"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_9.setText(_translate("MainWindow", "GitHub 仓库"))
        self.label_2.setText(_translate("MainWindow", "by zrydnoob"))
        self.label_3.setText(_translate("MainWindow", "欢迎使用"))
        self.label_4.setText(_translate("MainWindow", "不再为存档槽位而烦恼"))
        self.label_5.setText(_translate("MainWindow", "存档管理"))
        self.label_6.setText(_translate("MainWindow", "游戏存档"))
        self.label_20.setText(_translate("MainWindow", "本地存档"))
        __sortingEnabled = self.listWidget1.isSortingEnabled()
        self.listWidget1.setSortingEnabled(False)
        item = self.listWidget1.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget1.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("MainWindow", "存档信息"))
        self.label_17.setText(_translate("MainWindow", "所在区域"))
        self.label_18.setText(_translate("MainWindow", "玩家属性"))
        self.label_19.setText(_translate("MainWindow", "所用时间"))
        self.label_21.setText(_translate("MainWindow", "操作窗口"))
        self.pushButton_7.setText(_translate("MainWindow", "移动到本地"))
        self.pushButton_5.setText(_translate("MainWindow", "移动到游戏"))
        self.pushButton_4.setText(_translate("MainWindow", "复制到游戏"))
        self.pushButton_6.setText(_translate("MainWindow", "复制到本地"))
        self.pushButton_8.setText(_translate("MainWindow", "刷新"))
        self.label_7.setText(_translate("MainWindow", "存档备份"))
        self.label_8.setText(_translate("MainWindow", "设置"))
        self.label_10.setText(_translate("MainWindow", "游戏存档路径"))
        self.label_11.setText(_translate("MainWindow", "null"))
        self.pushButton_21.setText(_translate("MainWindow", "选择游戏存档目录"))
        self.pushButton_22.setText(_translate("MainWindow", "打开游戏存档目录"))
        self.label_12.setText(_translate("MainWindow", "本地存档路径"))
        self.label_13.setText(_translate("MainWindow", "null"))
        self.pushButton_23.setText(_translate("MainWindow", "选择本地存档目录"))
        self.pushButton_24.setText(_translate("MainWindow", "打开游戏存档目录"))
        self.label_9.setText(_translate("MainWindow", "关于"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Ori外置存档</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>作者:                zrydnoob</p><p>版本:                v0.1.0</p></body></html>"))
import resource_rc
